export const mockSizes = {
    '36':false,
    '37':false,
    '38':false,
    '39':false,
    '40': false,
    '41': false,
    '42': false,
    '43': false,
    '44': false,
    '45':false
};

export const mockBrands = {
    'Nike': false,
    'Puma': false,
    'Adidas': false,
    'Vans': false,
    'Calvin Klein': false,
};

export const mockColors = {
    'black': false,
    'white': false,
    'red': false,
    'green': false,
    'turquoise': false,
    'fuchsia': false,
    'yellow': false,
    'multicolor': false,
};
export const mockProducts = [
    {
        id: 1,
        title: 'Nike Air Max 90',
        imageUrl: 'https://i.pinimg.com/originals/ef/3e/52/ef3e5290da4e264a4bd180d18ea3519d.jpg',
        price: 100,
        currency: 'dollars',
        description: 'Nike Air Max 90 White / Grey / Turquoise',
        color: 'turquoise',
        brand: 'Nike',
        sizes: [40, 41, 42, 43, 44],
        sizesAvailable: [40, 42, 44],
    },
    {
        id: 2,
        title: 'ADIDAS ADVENTURE AOP WOVEN PANTS',
        imageUrl: 'https://static.footshop.com/419218/98095.jpg',
        price: 100,
        currency: 'dollars',
        description: 'Red',
        color: 'multicolor',
        brand: 'Adidas',
        sizes: [40, 41, 42, 43, 44],
        sizesAvailable: [40, 42, 44],
    },
    {
        id: 3,
        title: 'Adidas Down Regent',
        imageUrl: 'https://static.footshop.com/414022/84013.jpg',
        price: 200,
        currency: 'dollars',
        description: 'Collegiate Green',
        color: 'turquoise',
        brand: 'Adidas',
        sizes: [40, 41, 42, 43, 44],
        sizesAvailable: [40, 42, 44],

    },
    {
        id: 4,
        title: 'Nike Air Force 1 GTX',
        imageUrl: 'https://static.footshop.com/421519/86107.jpg',
        price: 179,
        currency: 'dollars',
        description: 'Flax/ Flax-Wheat-Gum Light Brown',
        color: 'yellow',
        sizes: [40, 41, 42, 43, 44],
        sizesAvailable: [42, 44],
        brand: 'Nike',
    },
    {
        id: 5,
        title: 'NIKE SPORTSWEAR WOVEN JACKET',
        imageUrl: 'https://static.footshop.com/392698/61408.jpg',
        price: 74.97,
        currency: 'dollars',
        description: 'Barely Volt/ White/ White/ Volt',
        color: 'white',
        sizes: [40, 41, 42, 43, 44],
        sizesAvailable: [43, 44],
        brand: 'Nike',
    },
    {
        id: 6,
        title: 'VANS SK8-HI 38 DX (ANAHEIM FACTORY)',
        imageUrl: 'https://static.footshop.com/350371/56593.jpg',
        price: 76.76,
        currency: 'dollars',
        description: 'Hoffman Fabrics/ Native Mix',
        color: 'yellow',
        brand: 'Vans',
        sizes: [40, 41, 42, 43, 44],
        sizesAvailable: [41, 43],

    },
    {
        id: 7,
        title: 'MAHARISHI LIBERTY DRAGON HOODED SWEAT',
        imageUrl: 'https://static.footshop.com/408313/95632.jpg',
        price: 300,
        currency: 'dollars',
        description: 'Black',
        color: 'black',
        brand: 'Puma',
        sizes: [40, 41, 42, 43, 44],
        sizesAvailable: [40, 42],
    },
    {
        id: 8,
        title: 'CHINATOWN MARKET SMILEY CHAMPION 3 RINGS SHORTS',
        imageUrl: 'https://static.footshop.com/411832/95380.jpg',
        price: 90,
        currency: 'dollars',
        description: 'Red',
        color: 'red',
        brand: 'Puma',
        sizes: [40, 41, 42, 43, 44],
        sizesAvailable: [41, 42],
    },
]
